- hosts: localhost
  connection: local
  vars:
    project: robustly
    gopath: /tmp/go_projects/{{project}}
    go_version: go1.9.4
    goroot: /usr/local/{{go_version}}
    vcpath: "{{gopath}}/src/github.com/VividCortex"
    artifacts:
      - robustly
  tasks:
    - command: echo $PWD
      register: d

    - file: >
        path={{vcpath}}
        state=directory
        recurse=yes

    - shell: "rm -rf {{vcpath}}/{{project}}"

    - shell: "cp -R {{d.stdout}} {{vcpath}}/{{project}}"

    - file: >
        path={{d.stdout}}/artifacts
        state=directory
        recurse=yes

    - command: "dep ensure -vendor-only"
      args:
        chdir: "{{vcpath}}/{{project}}"
      environment:
        GOROOT: "{{goroot}}"
        GOPATH: "{{gopath}}"
        PATH: "{{ ansible_env.PATH }}:{{goroot}}/bin:/usr/bin:/usr/local/bin"
        VERSION: "{{ version|default('') }}"
        

    - command: "./build"
      args:
        chdir: "{{vcpath}}/{{project}}"
      environment:
        GOROOT: "{{goroot}}"
        GOPATH: "{{gopath}}"
        VERSION: "{{version|default('')}}"
        PATH: "{{ ansible_env.PATH }}:{{goroot}}/bin:/usr/bin"

    - copy: src="{{vcpath}}/{{project}}/{{item}}" dest={{d.stdout}}/artifacts mode=0755
      with_items: "{{ artifacts }}"

    - set_fact: build_version="{{ lookup('pipe','artifacts/robustly --version') }}"

    - copy: >
        content="VERSION={{build_version.split(' ')[2]}}"
        dest=artifacts/.meta
