version: 2
jobs:
  build:
    working_directory: /go/src/github.com/VividCortex/robustly
    docker:
      - image: circleci/golang:1.9.4-stretch
    steps:
      - checkout
      - run: curl -L -o /go/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && chmod +x /go/bin/dep && dep version
      - run: dep ensure -v -vendor-only
      - run: go vet ./...
      - run: go test -race ./...
